version: '3'
services:
  h1:
    container_name: attacker
    privileged: true
    build:
      context: .
      dockerfile: csc2024-project3.Dockerfile
      args:
        PASSWORD: csc2024
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      Ransomware:
        ipv4_address: 172.18.0.2
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /usr/sbin/sshd -D &
        sleep infinity
    volumes: 
      - ../:/home/csc2024/109550160-110550029

  h2:
    container_name: victim
    privileged: true
    build:
      context: .
      dockerfile: csc2024-project3.Dockerfile
      args:
        PASSWORD: 123csc2024
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
    networks:
      Ransomware:
        ipv4_address: 172.18.0.3
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        /usr/sbin/sshd -D &
        sleep infinity
    volumes: 
      - ../Pictures/:/app/Pictures

networks:
  Ransomware:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16